### ISSUE TITLE
Unity adapter for NServiceBus6 and Unity 5.11.x

### ISSUE THREAD

**Issue by patrickrobbins** [Particular/NServiceBus.Unity#198] opened 2020-11-25 19:51 UTC
We have found a race condition in our current version of unity (5.5.8) and need to updated to the latest version of unity.  Right now we can't update to  NSB 7.  I'm going to look into updating based on release 8 to update the NSB6 code to use unity 5.11.  Is that something that you are willing to pull in and create an official package?

**Comment by lailabougria** [comment] 2020-11-27 07:27
Hi @patrickrobbins,

NSB6 is currently on [extended support](https://docs.particular.net/nservicebus/upgrades/supported-versions). Can you please [raise a support ticket](https://particular.net/support) so we can evaluate how to help you move forward?

Thank you!

**Comment by patrickrobbins** [comment] 2020-11-30 15:02
I have submitted a ticket.

**Comment by HEskandari** [comment] 2021-12-07 06:43
@patrickrobbins I'm closing this under the assumption that you have opened a ticket and the issue is dealt with. If you need further assistance, please do open a support ticket.

**Closed by HEskandari** 2021-12-07 06:43 UTC
